### PR TITLE
CMake: Use GNUInstallDirs when creating pkg-config files and installing MacOSX frameworks

### PR DESCRIPTION
**Pull request by adrianbroher**
* The generation of the pkg-config file uses hard coded file pathes to the library and include directories.  This will create an invalid pkg-config file when using distribution specific or manual set up library and include directories.  The first commit replaces those hard coded directory pathes with the fitting `CMAKE_INSTALL_FULL_*DIR` equivalent.

* MacOSX framworks are usually installed in one of `/Library/Frameworks`, `~/Library/Frameworks`, `/Network/Library/Frameworks` or `/System/Library/Frameworks` according to the [Installing Your Framework] documentation.  The current FRAMEWORK DESTINATION (which indicates the installation location of the framework) is set to `lib${LIB_SUFFIX}`, which makes it impossible to install the framework to the right location (the full path will be &lt;CMAKE_INSTALL_PREFIX&gt;/lib&lt;LIB_SUFFIX&gt;, so regardless of the chosen value for CMAKE_INSTALL_PREFIX a user cannot install the Framwork to the correct location).    Instead using the `CMAKE_INSTALL_PREFIX` directly, while providing non-optimal defaults, it is now possible to install the Framework at the right location.  For example

```
cmake -DCMAKE_INSTALL_PREFIX=/Library/Frameworks -DBUILD_FRAMEWORK=ON <glew_src_dir>
make
make install
```

will install the Framework correctly into the `/Library/Frameworks` directory.  This solution however is not optimal, as the default [CMAKE_INSTALL_PREFIX] value is `/usr/local` on UNIX.

[Installing Your Framework]: https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Tasks/InstallingFrameworks.html
[CMAKE_INSTALL_PREFIX]: https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html

### CODE REVIEW

**Comment by nigels-com** [comment]
Never mind the appveyor.com failure, that's not supposed to be triggering yet.

**Comment by nigels-com** [comment]
Does it make sense to default `CMAKE_INSTALL_PREFIX=/Library/Frameworks` in the `BUILD_FRAMEWORK=ON` case?

**Comment by adrianbroher** [comment]
> Does it make sense to default CMAKE_INSTALL_PREFIX=/Library/Frameworks in the BUILD_FRAMEWORK=ON case?

Problem here is that we can't determine if the user has set CMAKE_INSTALL_PREFIX because it always exist.  If the user decides to set the variable explicit to `/usr/local` and we just assume that this the default value and change it to `/Library/Frameworks` the script is doing something unexpected and completely different than the script was told by the user.  Just assuming CMAKE_INSTALL_PREFIX is set properly is a better way to solve this IMO.

**Comment by nigels-com** [comment]
I'm a bit inclined to force someone to hack the build to install a framework somewhere exotic (such as /usr/local), rather than imagine that everyone will read (and heed) the documentation.

I think that doing the right thing by default is an important priority.

Perhaps the better formulation is `BUILD_FRAMEWORK=/Library/Frameworks` - using the principle of least surprise.

**Comment by nigels-com** [comment]
Compromise proposal is to update the Readme.md documentation to recommend `-DCMAKE_INSTALL_PREFIX=/Library/Frameworks` in combination with `-DBUILD_FRAMEWORK=ON`

I do see your point, it's just a shame that it's a bit more awkward than we'd prefer.

**Comment by adrianbroher** [comment]
> Compromise proposal is to update the Readme.md documentation to recommend -DCMAKE_INSTALL_PREFIX=/Library/Frameworks in combination with -DBUILD_FRAMEWORK=ON

I have added another commit which documents all available targets and variables for CMake.  Could you please check if the doc is understandable?

**Comment by nigels-com** [comment]
Thanks for that, I think we're on the right track.

It does seem to me that we might consider renaming 'BUILD_UTILS' to 'GLEW_UTILS' along with 'BUILD_FRAMEWORK' becoming 'GLEW_FRAMEWORK'.

Having said that, I think I'll merge this with some typo fixups on top.

Cheers!

**Pull request merged**
