### PR TITLE
removed any linking dependences wrt libgl.so on Linux

### PR DESCRIPTION
**Pull request by mcecchetti**
The patch uses dlopen, dlsym for getting the entry point of glXGetProcAddressARB and so removing any linking dependences wrt libgl.so

I tested it on Windows too and it works fine, anyway there could be some issue on other platform.

I am evaluating to introduce a define switch in order to get a more clean solution, but it require to modify Perl scripts too. 

In the meanwhile any feedback on the current patch is welcome!

### CODE REVIEW

**Comment by nigels-com** [comment]
There are various failures in Travis:
https://travis-ci.org/nigels-com/glew/builds/123005011

**Comment by nigels-com** [comment]
To be honest, I'm doubtful of this kind of change being accepted into GLEW master branch.  The main reason is that GLEW has provided backwards compatibility for a long, long time.  Changing the binary interface would be a great inconvenience for a lot of projects, so it would only be done for a very strong reason.  From my own selfish point of view, I'm not much interested in maintaining the GLEW 1.x branch along side a GLEW 2.x one.  It might be necessary for MX mode, but hopefully not!

**Comment by mcecchetti** [comment]
I see, anyway, leaving aside for the moment what is the right branch to these changes, do you think there is interest in a version of the library which has no linking dependencies wrt libgl on Linux ?

At least here at LibreOffice it would be useful for removing some #ifdef / #endif boilerplate.

As for the failures in Travis I didn't notice that files under extensions/gl are generated and not tracked, so a file that should have been removed was still present.

**Comment by nigels-com** [comment]
I'm interested to know some more about the motivation for this. Is there an Open Office issue you could point me to?

**Comment by nigels-com** [comment]
One alternative is to link GLEW statically, along with an implementation of the function loader, rather than depending on libGL.so. Another approach is to omit GL from the link step, allowing and proving some other export that does the dlopen.

**Comment by mcecchetti** [comment]
Well for instance we would like to revert this commit: 
https://gerrit.libreoffice.org/gitweb?p=core.git;a=commit;h=96c1ae1d8e78ae8b9bd7d4001645cad24d62b720

**Comment by mmeeks** [comment]
Hi Nigel ! =)

The basic problem intersects with packaging - take for example VCL -our widget toolkit; we really want to use the OpenGL rendering backend there - but, on many Linux's that crashes and burns; other people want to use it headless. As such - we really want to drop the hard linkage to libGL.so that VCL has - since that forces everything to link to GL =) [ while in fact this is just an implementation detail of an optional, and run-time probed backend ]. The problem with everything linking to libGL.so propagates up the stack - so Linux packagers start to have to ship GL backends since they get automatic dependencies on that (and we can't start without a libGL.so) and ... so it goes on =).

Obviously we don't want to break the ABI or backwards compatibility. Would it be possible to have a #define that affects how the header behaves - so we can have the old (direct linking) symbols, or (conditionally) the new ones with a #define GLEW_NO_GL_LINKAGE (I busk a name for it ;-)

This would be really appreciated ! and of course, helps us keep GL enabled everywhere, for those that want to use it =)

Thanks for picking up glew & maintaining it too !

**Comment by nigels-com** [comment]
I see.  

```
$ nm -D lib/libGLEW.so | grep ' U '
                 U glXGetClientString
                 U glXGetProcAddressARB
                 U glXQueryVersion
```

**Comment by nigels-com** [comment]
I havn't been following the GLEW alternatives too closely, but there are some alternatives to look into:
[opengl.org](https://www.opengl.org/wiki/OpenGL_Loading_Library), [reddit](https://www.reddit.com/r/opengl/comments/3m28x1/glew_vs_glad/).

Having said that, I think there is some possibility of accomodating this requirement in GLEW, but it would need to be a #define variant, and having just dropped MX support, I'm a bit shy of taking on a new variant, especially if it look destabilising.  I really want to release GLEW 2.0.0 as-is rather than churn the stuff all over again.

**Comment by nigels-com** [comment]
The other possibility in my mind is to revisit [Regal](https://github.com/p3/regal), prune it back to bare essentials and rename that to something new.  It was always my intention to generate GLEW with the Regal codegen scripts, but it would be a fair effort to do the migration...

**Comment by nigels-com** [comment]
Declining to merge this, due to API and ABI compatibility considerations.

**Comment by mcecchetti** [comment]
Hi Nigel,

Lately I have been busy in fixing some high prio LibreOffice problem, however there is still interest from our side to introduce a solution which has no linking dependency wrt libGL.
We'll take care to implement it so that there is no API or ABI compatibility issue. Consider my current implementation just a way to get in touch with the context of the problem. Obviously, we don't want to interfere with your release schedule, in any way.

**Comment by nigels-com** [comment]
I don't see a way around this, in terms of maintaining API/ABI compatibility.  I wouldn't ordinarily tell users to switch away from GLEW, but in this case I do think you should consider alternatives.

**Pull request closed without merging**
