### PR TITLE
Add lgtm.yml configuration file

### PR DESCRIPTION
**Pull request by alexey-tereshenkov-oxb**
Having this file in the root of the project will allow LGTM.com use the custom configuration to analyze C++ code of the project. I am a user of this library and am very interested to see if there are any issues we should be aware of.

Currently, C++ source code of the project on [LGTM.com](https://lgtm.com/projects/g/nigels-com/glew/?mode=list) is not analyzed because there is an extra step to run `make` inside the `auto` directory to build from source which LGTM.com won't be able figure out automatically.

I have tested this configuration and it [worked successfully](https://lgtm.com/logs/d96856be36a69c67990e9a3daac8484926e4e0a6/lang:cpp) analyzing the C++ source code of the project.

Once the configuration file of this PR is in the master, next time LGTM.com will attempt to analyze the C++ code, it should pick it up and the analysis results will be available online on the project page.

### CODE REVIEW

**Comment by nigels-com** [comment]
Can it be named '.lgtm.yml' ?

**Comment by alexey-tereshenkov-oxb** [comment]
> Can it be named `.lgtm.yml` ?

Absolutely - I've renamed the file to hide it. Many thanks for looking into this.

**Comment by alexey-tereshenkov-oxb** [comment]
@nigels-com hi there! Just checking if there is anything else you'd like to amend before accepting the PR? Many thanks!

**Comment by alexey-tereshenkov-oxb** [comment]
@nigels-com hey Nigel, just checking in whether you'd still be interested in having this merged so that we could get this analyzed on lgtm.com? Thanks!

**Comment by nigels-com** [comment]
Done!  And thanks.

**Pull request merged**
