### PR TITLE
Can now build 32-bit binaries on 64-bit linux

### PR DESCRIPTION
**Pull request by dimi309**

### CODE REVIEW

**Comment by nigels-com** [comment]
Looks good.  Any chance we can extend the Travis build coverage for this?

**Comment by dimi309** [comment]
If you mean annexing the conan build to the regular build with travis, sure, I can have a go at it. I just didn't want to mess with your continuous integration without being invited to :) But if I got it wrong please let me know.

**Comment by nigels-com** [comment]
I think I'm confused about building GLEW with conan.  Where is the `conanfile.txt` that the documentation refers to?  Do I have to use `cmake`?  GLEW doesn't depend on much, am I barking up the wrong tree?

**Comment by dimi309** [comment]
Conan is not so much a build system but rather a package management system that drastically reduces the steps needed to reference existing libraries that have been packaged with it. It is architected in a way that allows it to interact with and encapsulate any compiler / build system like cmake, autotools, Visual Studio, MinGW or Xcode. In that sense, CMake is not a prerequisite when using conan. You will just find that many conan packages use it, either for building the library they contain itself, or for building the test that ensures that the library works.

So conan's added value is not so much in altering the build configuration but the production and easy consumption of cross-platform packages each containing a library, information about its dependencies on other libraries, a "recipe" (conanfile.py) for building it and binaries corresponding to various os architectures. You reference a conan package by listing it in your project's recipe. conanfile.txt is the most concise and easy to use recipe format, while conanfile.py offers more functionality and is a prerequisite for building a package rather than simply a project that consumes packages. Then, when you build your project with conan, it first checks which packages your have referenced. It downloads and sets up their binaries for you in a local cache, which can be reused across projects. If your cpu architecture and build options cannot match a precompiled binary, the package's recipe is used to compile it on your machine before storing it in the local cache. The same is repeated for packages referenced by the packages you have referenced, together with their own dependencies, etc.

When I think about tools I have already used and ask myself what does conan most closely resemble, the first things that leap to mind are maven or nuget.

If you'd like to see how easy it is to create a project that uses conan exclusively for referencing libraries, you can have a look at this little game I've made, which references my own game engine, small3d, which in turns references the GLEW package I've put together (please be kind, this is not the sort of software I write for a living xD): https://github.com/dimi309/small3d-tutorial/tree/master/AvoidTheBug3D
In my humble opinion, for established libraries like GLEW, conan is not so much a replacement of their build systems. Replacing them or forcing consumers of such libraries to use conan would probably not be a realistic thing to do. It is rather something that can encapsulate the build procedure making such libraries easier to consume in a much simpler and faster way than was ever available before. In the case of GLEW for example, on Windows, you replace building or downloading its archive, copying lib and dll files to where they need to be, making sure you pick up the right version (static / dynamic lib, build/debug) and configuring your linker with adding a line in a conanfile. The advantages may seem less obvious on a linux system with its built-in package manager, but they become apparent not only on Win and MacOS but also by the fact that a conan-based build works exactly the same across all of these systems (and can even work on android and raspberry pi afaik).

For GLEW, perhaps the conan configuration we have already added to its repository is the best solution. Anyone can just run `conan create` from within `build/conan` if they would like to package it locally. It is also easy to set up the project to run automated builds and publish packages to bintray or even another repository (conan is a distributed package manager in any case, sort of like git is a distributed vcs), like I do here:

https://github.com/dimi309/glew/tree/2.1.0/conan

publishing the package here:

http://bintray.com/dimi309/conan-packages/glew%3Adimi309

through travis & appveyor:

https://travis-ci.org/dimi309/glew/builds/303868370?utm_source=github_status&utm_medium=notification

https://ci.appveyor.com/project/coding3d/glew/build/1.0.24

(Like I've said, if you would ever like to take this over, I have no problem pulling down my own version. What I win in either case is being able to use GLEW via conan :) )

What I thought you asked yesterday and I thought you might like to see, was an added parameter in your .travis.yml file so that you can switch between your clean build and one that also incorporates conan pacakaging. Of course, that might make the travis file look a bit more complicated, but let me know if you'd like me to have a look.

One again, with my apologies for spamming them, I would also like to ping @drodri and @lasote, the founders of conan, in case they would like to add something to this conversation.

**Comment by nigels-com** [comment]
Thank you so much for the detailed explanation.  It all makes sense now!  Cheers!

**Comment by dimi309** [comment]
You're welcome!

**Pull request merged**
