### PR TITLE
[parse_xml] replace OptionParser with ArgumentParser according to Python 3.2+ recommendation.

### PR DESCRIPTION
**Pull request by TheVice**
Hello.

Starting from Python version 3.2 OptionParser is deprecated - instead ArgumentParser recommend to use, so proposed made such change in Python script parse_xml.

Thank you.

### CODE REVIEW

**Comment by nigels-com** [comment]
Whew!  It doesn't break on Python 2.7?  

https://docs.python.org/2/library/argparse.html

**Comment by TheVice** [comment]
No.

It was added for Python 2.7 too.

**Comment by nigels-com** [comment]
Unfortunately there is a merge conflict for this.  Do you mind rebasing it?

**Comment by TheVice** [comment]
@nigels-com sure. Please note that for binary writing - encoding of string required, otherwise TypeError may happens at some environment(Python 3).

So at this case [addition commit](https://github.com/nigels-com/glew/pull/220/commits/e55752c8e03ac9c698c8aec6578cdec9e564c479) after 'rebase' was required is for forward compatibility only.

**Comment by nigels-com** [comment]
...sigh...  It's sad what a mess the Python landscape is nowadays.  It wasn't always this way.

**Comment by nigels-com** [comment]
Thanks for the contribution.  (Aside from my near daily irritation with Python, which is none of your doing!)

**Pull request merged**
