### PR TITLE
Core gl context

### PR DESCRIPTION
**Pull request by urkle**
more complete solution to #24.

1. Takes the base approach of building up a hash list but for all extension lists (GL, GLX, and WGL) so everything is consistent.
2. Then it also handles ensuring the "core" extensions are loaded for a 3.2+ context (as extensions are ONLY presented past 3.2)
3. This also works cleanly with MX builds of glew.

Tested and verified on Windows, OS X and Linux in 2 AAA game titles.

### CODE REVIEW

**Comment by nigels-com** [comment]
I just started looking into this merge request, it's more significant than usual for GLEW, so it might take some digesting.  I do agree that the extension descriptions need to be extended with something like these LOAD directives.  I wonder if we can simply match anything with no spaces or () - not an enum, and not a function, just for simplicity of the file format.  My other initial thought is if this hash table is leaked at shutdown.  Can we determine a compile-time size based on the set of extensions known to GLEW, and simply ignore at runtime the ones that GLEW doesn't know about?  This way our "hash" could simply be a string-sorted array of extensions with a corresponding GLboolean for available or not.

**Comment by nigels-com** [comment]
I created a milestone "GLEW 2.0" on Sourceforge for keeping track of the pre-existing bugs and discussion concerning Core context support.  FYI: https://sourceforge.net/p/glew/bugs/milestone/2.0.0/

**Comment by urkle** [comment]
I never really liked that it "leaked", but then when you are quiting your game it doesn't really matter as all memory will be freed at that point regardless..    a "leak" is only a concern if it's continually being allocated and never freed....    

Going through the list of "known" extensions only could work.  I'll have to fiddle with that to see how easy it would be to accomplish.

One thing we did find out in our 2 ports using this branch..  one of the extensions ( https://www.opengl.org/registry/specs/ARB/vertex_type_2_10_10_10_rev.txt ) changes behavior in a 3.2+ context.  e.g. not all of the functions are available in a 3.2+ core context.  Which on OS X means they are not available (as OS X only provides 2.1 OR a 3.2+ core profile and that extension is not available in the 2.1 context).  This caused some "annoying" fun requiring the porter to patch the extension method to not fail when a few methods were not available.

**Comment by nigels-com** [comment]
Yes, I understand about the memory leak.  But I would broadly consider it a regression for GLEW to start doing that, and it's bound to impact somewhere - in automated testing especially.  My broad idea is to have a list of all extensions known to GLEW, sort those and store in a const static array.  These can be looked up in O(log n) time.  Corresponding to that, and array of GLboolean to indicate enabled or not.

As for "some methods not available, depending on the context", yes that's another well known (to me) lurking issue.  It affects DSA and Nvidia path rendering in particular.

**Comment by urkle** [comment]
let me know how you want me to rework things and I shall.  My goal is to get core contexts supported in GLEW directly..

**Comment by urkle** [comment]
BTW I LOVE GLEW and use it in every port I do.. (33 and counting!)  Now, once I get CORE contexts working, I want to start on GLEW-ES :)

**Comment by nigels-com** [comment]
My perl is fairly limited.  I've got a feeling there is going to be a lot of perl wrangling to get this done.

**Comment by urkle** [comment]
well, yeah I figured..   I'm pretty good with my perfu, so Just let me know how you want things done and I'll do the leg work to get it done.

**Comment by nigels-com** [comment]
Some more comments looking at a diff of the generated sources.

1. GLEWHashList is added to the header glew.h, but hopefully this is an implementation artifact and can be hidden from the interface.  For MX I'd recommend a void pointer.

2. With the calls to _glewHashListExists, it would be nice to use "const char *" and remove the cast.

```
GLEW_3DFX_multisample = _glewHashListExists(ext_hashlist, (const GLubyte *)"GL_3DFX_multisample");
```

3. Perhaps all these extension-enabled flags can be set when the string/strings are queried.  We could have a const char ** of extension names, and a GLboolean ** of pointers to the extension enable variables.

4. With the declarations of the _glewInit functions, I think we probably ought to go ahead and pre-declare all of them.  The complication of course is if, say, GL_VERSION_3_0 is defined, but GL_ARB_framebuffer_object is not.  I think the reality here is that extensions are now very much entangled with each other.  GLEW is gradually going to need to accomodate that reality.

```
#ifdef GL_VERSION_3_0
static GLboolean _glewInit_GL_ARB_framebuffer_object(GLEW_CONTEXT_ARG_DEF_INIT);
...
static GLboolean _glewInit_GL_VERSION_3_0 (GLEW_CONTEXT_ARG_DEF_INIT)
{
  GLboolean r = GL_FALSE;
```

But overall, I'm (a bit) less daunted than just going by the code generation changes.

**Comment by nigels-com** [comment]
OK, it's merely a first-stab, but for some of the previous discussion I did some work in a core-context branch: https://github.com/nigels-com/glew/commits/core-context

Discussion, scrutiny, etc welcome.  (It's not perfect, yet)

- Nigel

**Comment by urkle** [comment]
The advantage of the HashList over the char** is that the hashlist can reach O(1) in many cases, vs the char** is O(n) (not sure where you got O(log n) for that)..  Although that is essentially what you were doing before is O(n).. so it's no slower than the current glew extension scanning.  Now, another side-affect of the master char** list is that for a core context the # of extension is significantly smaller.  So we'd be scanning through a lot of entries in that list which are never going to show up in a core context.

**Comment by nigels-com** [comment]
It's O(log n) to binary search a sorted array of extension name strings.  If we could pre-bake a fixed-size hash table in perl, I'd be OK with that.  But that seems like some extreme perl-fu! :-)

**Comment by nigels-com** [comment]
http://en.wikipedia.org/wiki/Binary_search_algorithm

**Comment by nigels-com** [comment]
Alright, I made a fresh push to the core-context branch.  It's using an array of GLboolean to represent what was found in the extension string.  Also, and array of GLboolean pointers to access the per-extension flags which can be auto-detected in "experimental" mode.  This way the output of glewinfo perfectly matches the master branch.  Two next steps, add the core alternative to glGetString(GL_EXTENSIONS), and support this for GLEW MX.

**Comment by nigels-com** [comment]
Alright, so I put the GL_VERSION_3_0 glStringi path in too, and enabled core context mode for glewinfo on Mac 10.9.  It seems like it works, although various odds and ends such as Windows, Linux and MX mode.  If there is enough there in the core-context branch to enable any testing, that would be helpful.

**Comment by urkle** [comment]
So, I've found another "fun" issue with the current model of loading extensions.    
ARB_texture_storage has some conditions in the definition that state "IF EXT_direct_state_access is also defined these other functions are available too.".   specifically the glTextureStorage[123]DEXT functions.   However the code generated requires the existence of those methods, and therefor fails to enable the extension.

**Comment by nigels-com** [comment]
Agreed.  There are issues with complicated extension dependency.  See also: https://github.com/nigels-com/glew/issues/15

**Comment by jukkaho** [comment]
Is the memory release problem the only thing holding core context support back? It seems to be the primary issue with all the proposed patches. Couldn't you just use atexit() to release the memory? It should have deterministic order in C++ as well regarding destructor calling order.

**Comment by nigels-com** [comment]
It's one of the problems, for sure.  atexit() is a possibility if it's well supported across platforms and won't conflict with other libraries and applications using the same mechanism.  It's been a while since I looking into this, perhaps there is more of the core-context4 branch that can be brought across to the mainline now that 1.13.0 is released.  Building it just now, the obvious problem is lack of support for MX mode.  But aside from that I'd welcome feedback on the core-context4 branch in particular

-- Nigel.

**Comment by jukkaho** [comment]
I tested core-context4 branch on Windows with VS2013 (Update 5) and OpenGL 3.2 (both core and compatibility profiles) with an Nvidia GPU without using glewExperimental. All the basic functionality I need (including detecting extensions) seem to work perfectly so far.

**Comment by nigels-com** [comment]
That's encouraging indeed.  One of my thoughts concerning core context support is to switch from the current core/extension files to XML extracted from the official opengl.org ones.  When it comes to expressing the deprecated functions and so on, I'm a bit reluctant to continue incrementing the current scheme.

**Comment by jukkaho** [comment]
I'm sure switching to XML definitions is better for the future of the library. However I would be very happy if you plan to release a core profile compatible version of GLEW before starting that development. I would expect switching to a different generation method to be more GLEW 2.0 material as you can do larger API changes at the same time if necessary. Of course it might make sense to backport some of that code for 1.3 series as well if it makes maintenance significantly easier.

**Comment by nigels-com** [comment]
One thing that GLEW ought to deal with is skipping the deprecated functions depending on the version, for core contexts.  But you're suggesting that isn't necessary in practice?  You're saying that your apps are working for Core contexts, and it's merely the MX support that remains?

-- Nigel

**Comment by stopiccot** [comment]
Tested core-context4 branch on OS X 10.10 with core profile. Can you explain please `glGenVertexArrays` is not initialized by glewInit() call?

**Comment by nigels-com** [comment]
Ah, yes.  glGenVertexArrays can be via OpenGL 3.0 core, or ARB_vertex_array_object which was rolled into OpenGL 3.0.  GLEW is expecting ARB_vertex_array_object in the extension string(s).  I think the Mac driver is being a bit unique in supporting OpenGL 3.0 without also advertising the corresponding ARB extension.  If you look at the details of this pull request, the LOAD (which the OpenGL XML calls "require reuse") is what is needed for  glGenVertexArrays on Mac.

**Comment by nigels-com** [comment]
Please try a fresh build of core-context4 on OS X with core profile.  I implemented per-extension "reuse" in the toolchain so that OpenGL 3.0 loads the extensions: GL_ARB_framebuffer_object GL_ARB_map_buffer_range GL_ARB_uniform_buffer_object GL_ARB_vertex_array_object

Please confirm if this step makes glGenVertexArrays available to you.

**Comment by stopiccot** [comment]
It helped thanks. It's seems that Apple driver does not report ARB_vertex_array_object extension cause it's a mandatory part of OpenGL 3.0 and core context version is 4.1.

**Comment by nigels-com** [comment]
If it's not too much bother, I'd be interested to see the output of glewinfo for Yosemite core context.  I assume there would be deprecated functions that GLEW is still trying to load?

**Comment by stopiccot** [comment]
Running `glewinfo -profile core` produces such output: https://gist.github.com/stopiccot/2f4a2ebbf88db4db6204

But it seems to initialize compatibility profile anyway

**Comment by stopiccot** [comment]
There is probably unneeded check here:

``` c
  #if MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_7
  if (params->profile & GL_CONTEXT_CORE_PROFILE_BIT)
  {
    if (params->major==3 && params->minor>=2)
    {
      contextAttrs[i++] = kCGLPFAOpenGLProfile;                                /* OSX 10.7 Lion onwards */
      contextAttrs[i++] = (CGLPixelFormatAttribute) kCGLOGLPVersion_3_2_Core;  /* 3.2 Core Context      */
    }
  }
  #endif
```

**Comment by nigels-com** [comment]
Oh, OK. Some more handling for newer than 10.7.  Got it.

**Comment by nigels-com** [comment]
What about for:
glewinfo -version 3.2 -profile core -flag forward

**Comment by stopiccot** [comment]
I've commented out version check. Here is what I get:
https://gist.github.com/stopiccot/ec37e10a7d1721f6bf7c

**Comment by jukkaho** [comment]
> One thing that GLEW ought to deal with is skipping the deprecated functions depending on the version, for core contexts. But you're suggesting that isn't necessary in practice? You're saying that your apps are working for Core contexts, and it's merely the MX support that remains?

GLEW should skip deprecated functions for core contexts etc. for sure. However, current fixes are a big improvement already. Previously, for example, extensions were not found at all and it was a showstopper for me. These fixes make GLEW usable even when they are not yet perfect.

**Comment by nigels-com** [comment]
Yes, I hear you.  Aside from MX I'd quite like to merge core-context4 to master and continue on.

**Comment by nigels-com** [comment]
Some core profile support for GLEW was merged to the master branch recently, in preparation for a GLEW 2.0 release.  If any is able to do some testing with their core-context applications, that would be great.  There is probably more work to be done, but it's a good step forward, I think.

**Comment by nigels-com** [comment]
Appreciate the work done on this approach, even though I decided against this approach, in the end.  Closing this.

**Comment by mehditlili** [comment]
I get that exact same problem on Ubuntu 18.04 with libglew2.0 when setting:
```
  glutInitContextProfile(GLUT_CORE_PROFILE);
  glutInitContextVersion(4, 5);
  glutCreateWindow ("Window");
  printf("OpenGL supported Extensions %s: \n", glGetString(GL_EXTENSIONS));
```

I get none printed. I need core profile because the normal profile has a shading language version 1.30, which is 10 years old.

Here is the output of `glxinfo | grep OpenGL`

```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 19.2.1
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 19.2.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

**Pull request closed without merging**
