### PR TITLE
Update support for Cygwin 2.10.0 - based on MSYS toolchain config.

### PR DESCRIPTION
**Pull request by tornado1717**

### CODE REVIEW

**Comment by nigels-com** [comment]
So nowadays there is no X11 as part of Cygwin?

**Comment by tornado1717** [comment]
I believe it's an add-on that I didn't install.  I'm using base Cygwin + SDL 2.

**Comment by tornado1717** [comment]
For reference, my app's makefile contains "-lSDL2 -lOpenGL32 -lGLEW"

**Comment by nigels-com** [comment]
I've been away from Windows for a while.

Perhaps we ought to add a copy of this config as _Makefile.cygwin-x11_ ?

I don't have a good impression of which one ought to be the default, but I don't mind changing it over.

**Comment by tornado1717** [comment]
Good idea.  I went with Makefile.cygwin-x11 as the one with X11 support because I just like that naming scheme a little better.

**Comment by nigels-com** [comment]
Merged for upcoming GLEW release.  Thanks for the contribution.

**Pull request merged**
