### PR TITLE
Patch gl nvx linked gpu multicast

### PR DESCRIPTION
**Pull request by amhagan**
Added GL_NVX_linked_gpu_multicast

### CODE REVIEW

**Comment by nigels-com** [comment]
The link to the spec doesn't seem to work.
Does anyone know if the spec is available?
http://developer.download.nvidia.com/opengl/specs/GL_NVX_linked_gpu_multicast.txt

**Comment by amhagan** [comment]
[GL_NVX_linked_gpu_multicast.txt](https://github.com/nigels-com/glew/files/74390/GL_NVX_linked_gpu_multicast.txt) is in the the latest version of Nvidia Design Works. I assume at some point it will be hosted on the opengl website ?


The nvpro-samples also outline the extension.. 
https://github.com/nvpro-samples/gl_multicast/blob/master/main.cpp

**Comment by nigels-com** [comment]
Thanks for digging out the spec file.  This means I can slip it into the upstream `glfixes` repository rather than baking it into GLEW directly.  It winds up like this in `glew.h`, which looks right to me:

```
/* ---------------------- GL_NVX_linked_gpu_multicast ---------------------- */

#ifndef GL_NVX_linked_gpu_multicast
#define GL_NVX_linked_gpu_multicast 1

#define GL_LGPU_SEPARATE_STORAGE_BIT_NVX 0x0800
#define GL_MAX_LGPU_GPUS_NVX 0x92BA

typedef void (GLAPIENTRY * PFNGLLGPUCOPYIMAGESUBDATANVXPROC) (GLuint sourceGpu, GLbitfield destinationGpuMask, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srxY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei width, GLsizei height, GLsizei depth);
typedef void (GLAPIENTRY * PFNGLLGPUINTERLOCKNVXPROC) (void);
typedef void (GLAPIENTRY * PFNGLLGPUNAMEDBUFFERSUBDATANVXPROC) (GLbitfield gpuMask, GLuint buffer, GLintptr offset, GLsizeiptr size, const void *data);

#define glLGPUCopyImageSubDataNVX GLEW_GET_FUN(__glewLGPUCopyImageSubDataNVX)
#define glLGPUInterlockNVX GLEW_GET_FUN(__glewLGPUInterlockNVX)
#define glLGPUNamedBufferSubDataNVX GLEW_GET_FUN(__glewLGPUNamedBufferSubDataNVX)

#define GLEW_NVX_linked_gpu_multicast GLEW_GET_VAR(__GLEW_NVX_linked_gpu_multicast)

#endif /* GL_NVX_linked_gpu_multicast */
```

I'll follow up shortly with a download link for a fresh Travis build including this.

**Comment by nigels-com** [comment]
Just for the record, there are other extensions winding up in GLEW in this manner too:

```
$ git diff --stat master
 gl/specs/ANGLE/depth_texture.txt            | 402 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 gl/specs/ANGLE/framebuffer_blit.txt         | 437 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 gl/specs/ANGLE/framebuffer_multisample.txt  | 363 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 gl/specs/ANGLE/instanced_arrays.txt         | 359 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 gl/specs/ANGLE/pack_reverse_row_order.txt   | 168 ++++++++++++++++++++++++++++++
 gl/specs/ANGLE/program_binary.txt           |  94 +++++++++++++++++
 gl/specs/ANGLE/texture_compression_dxt.txt  | 163 +++++++++++++++++++++++++++++
 gl/specs/ANGLE/texture_usage.txt            | 202 ++++++++++++++++++++++++++++++++++++
 gl/specs/ANGLE/timer_query.txt              | 591 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  gl/specs/ANGLE/translated_shader_source.txt | 118 +++++++++++++++++++++
 gl/specs/ARB/direct_state_access.txt        |   9 ++
 gl/specs/ARB/draw_elements_base_vertex.txt  |   8 +-
 gl/specs/ARB/sample_locations.txt           |   2 +-
 gl/specs/EXT/vertex_weighting.txt           |   4 +-
 gl/specs/INTEL/texture_scissor.txt          |   2 +-
 gl/specs/KHR/context_flush_control.txt      |   6 +-
 gl/specs/KHR/debug.txt                      |   4 +-
 gl/specs/NVX/linked_gpu_multicast.txt       | 379 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 gl/specs/REGAL/ES1_0_compatibility.txt      | 113 ++++++++++++++++++++
 gl/specs/REGAL/ES1_1_compatibility.txt      |  95 +++++++++++++++++
 gl/specs/REGAL/enable.txt                   | 103 +++++++++++++++++++
 gl/specs/REGAL/error_string.txt             |  94 +++++++++++++++++
 gl/specs/REGAL/extension_query.txt          |  95 +++++++++++++++++
 gl/specs/REGAL/log.txt                      | 107 +++++++++++++++++++
 gl/specs/REGAL/proc_address.txt             |  88 ++++++++++++++++
 25 files changed, 3991 insertions(+), 15 deletions(-)
```

**Comment by nigels-com** [comment]
Yep, looks good to me.

Try this snapshot to confirm:
https://glew.s3.amazonaws.com/nigels-com/glew/61/61.1/glew-2.0.0.tgz

**Comment by nigels-com** [comment]
I'll leave this pull request open (a while)  in case there is anything to follow up on.

**Pull request closed without merging**
